services:
 mysql:
  container_name: mysql-sql
  image: mysql:latest #The official MySQLSQL image from Docker Hub.
  environment:
   MYSQL_ROOT_PASSWORD: password
   #PGDATA: /var/lib/postgresql/data #Specifies the directory where PostgreSQL will store its data.
   MYSQL_DATABASE: networkdb #This is the name of the default database to be created in MySQL as "networkdb".
  volumes:
   - mysql:/var/lib/mysql #This line mounts a volume named "mysql" into the container at the directory "/var/lib/". This is used to persist PostgreSQL data outside of the container.
  ports:
   - 3307:3307
  networks:
   - spring-demo
  restart: unless-stopped
 
 mail-dev:
  container_name: mail-dev-bsn
  image: maildev/maildev
  ports:
   - 1080:1080
   - 1025:1025
    
   
networks:
 spring-demo:
  driver: bridge
   
volumes:
 mysql:
  driver: local